export const GET_ISSUE_REQUEST = 'GET_ISSUE_REQUEST';
export const GET_ISSUE_SUCCESS = 'GET_ISSUE_SUCCESS';
export const GET_ISSUE_FAILURE = 'GET_ISSUE_FAILURE';

export const CHANGE_STATUS_REQUEST = 'CHANGE_STATUS_REQUEST';
export const CHANGE_STATUS_SUCCESS = 'CHANGE_STATUS_SUCCESS';
export const CHANGE_STATUS_FAILURE = 'CHANGE_STATUS_FAILURE';
export const CHANGE_STATUS_PROBLEM = 'CHANGE_STATUS_PROBLEM';

export const GET_ISSUES_QUEUE_REQUEST = 'GET_ISSUES_QUEUE_REQUEST';
export const GET_ISSUES_QUEUE_SUCCESS = 'GET_ISSUES_QUEUE_SUCCESS';
export const GET_ISSUES_QUEUE_FAILURE = 'GET_ISSUES_QUEUE_FAILURE';

export const LOAD_TIMEENTRIES_REQUEST = 'LOAD_TIMEENTRIES_REQUEST';
export const LOAD_TIMEENTRIES_SUCCESS = 'LOAD_TIMEENTRIES_SUCCESS';
export const LOAD_TIMEENTRIES_FAILURE = 'LOAD_TIMEENTRIES_FAILURE';
export const LOAD_TIMEENTRIES_PROBLEM = 'LOAD_TIMEENTRIES_PROBLEM';

export const POST_TIMEENTRY_PROBLEM = 'POST_TIMEENTRY_PROBLEM';
export const POST_TIMEENTRY_FAILURE = 'POST_TIMEENTRY_FAILURE';
