export const CHANGE_STATUS_REQUEST = 'CHANGE_STATUS_REQUEST'
export const CHANGE_STATUS_SUCCESS = 'CHANGE_STATUS_SUCCESS'
export const CHANGE_STATUS_FAILURE = 'CHANGE_STATUS_FAILURE'
export const CHANGE_STATUS_PROBLEM = 'CHANGE_STATUS_PROBLEM'

export const GET_ISSUES_QUEUE_REQUEST = 'GET_ISSUES_QUEUE_REQUEST'
export const GET_ISSUES_QUEUE_SUCCESS = 'GET_ISSUES_QUEUE_SUCCESS'
export const GET_ISSUES_QUEUE_FAILURE = 'GET_ISSUES_QUEUE_FAILURE'

export const LOAD_TIMEENTRIES_REQUEST = 'LOAD_TIMEENTRIES_REQUEST'
export const LOAD_TIMEENTRIES_SUCCESS = 'LOAD_TIMEENTRIES_SUCCESS'
export const LOAD_TIMEENTRIES_FAILURE = 'LOAD_TIMEENTRIES_FAILURE'
export const LOAD_TIMEENTRIES_PROBLEM = 'LOAD_TIMEENTRIES_PROBLEM'

export const POST_TIMEENTRY_PROBLEM = 'POST_TIMEENTRY_PROBLEM'
export const POST_TIMEENTRY_FAILURE = 'POST_TIMEENTRY_FAILURE'

export const TOGGLE_NEW_ISSUE = 'TOGGLE_NEW_ISSUE'

export const CREATE_NEW_ISSUE_REQUEST = 'CREATE_NEW_ISSUE_REQUEST'
export const CREATE_NEW_ISSUE_SUCCESS = 'CREATE_NEW_ISSUE_SUCCESS'
export const CREATE_NEW_ISSUE_FAILURE = 'CREATE_NEW_ISSUE_FAILURE'
export const CREATE_NEW_ISSUE_PROBLEM = 'CREATE_NEW_ISSUE_PROBLEM'

export const GET_PROJECTS_REQUEST = 'GET_PROJECTS_REQUEST'
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS'
export const GET_PROJECTS_FAILURE = 'GET_PROJECTS_FAILURE'
export const GET_PROJECTS_PROBLEM = 'GET_PROJECTS_PROBLEM'

export const GET_MEMBERSHIPS_REQUEST = 'GET_MEMBERSHIPS_REQUEST'
export const GET_MEMBERSHIPS_SUCCESS = 'GET_MEMBERSHIPS_SUCCESS'
export const GET_MEMBERSHIPS_FAILURE = 'GET_MEMBERSHIPS_FAILURE'
export const GET_MEMBERSHIPS_PROBLEM = 'GET_MEMBERSHIPS_PROBLEM'
