//fake
export const CHANGE_STATUS = 'CHANGE_STATUS';
export const GET_AVAILABLE_STATUSES = 'GET_AVAILABLE_STATUSES';

//real
export const GET_ALL_STATUSES = 'GET_AVAILABLE_STATUSES';

export const CHANGE_STATUS_REQUEST = 'CHANGE_STATUS_REQUEST';
export const CHANGE_STATUS_SUCCESS = 'CHANGE_STATUS_SUCCESS';
export const CHANGE_STATUS_FAILURE = 'CHANGE_STATUS_FAILURE';

export const GET_AVAILABLE_STATUSES_REQUEST = 'GET_AVAILABLE_STATUSES_REQUEST';
export const GET_AVAILABLE_STATUSES_SUCCESS = 'GET_AVAILABLE_STATUSES_SUCCESS';
export const GET_AVAILABLE_STATUSES_FAILURE = 'GET_AVAILABLE_STATUSES_FAILURE';

export const GET_TASKS_QUEUE_REQUEST = 'GET_TASKS_REQUEST';
export const GET_TASKS_QUEUE_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_QUEUE_FAILURE = 'GET_TASKS_FAILURE';
